// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gmdkbpylziflwtvuqxjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdtZGticHlsemlmbHd0dnVxeGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4NTAwOTgsImV4cCI6MjA3MDQyNjA5OH0.X0p_Ld30anxZ2AOZkHU9JH4qyuQh5j46zqxW-UAw-08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});